eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://localhost:8773/eureka/,http://localhost:8774/eureka/

server:
  port: 8764

spring:
  application:
    name: service-ribbon