server:
  port: 8769

spring:
  zipkin:
    base-url: http://134.175.126.108:9411
  application:
    name: zipkin-from

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
