eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8767

spring:
  application:
    name: service-zuul

zuul:
  routes:
    api-a:
      path: /hi/**
      serviceId: service-hi
    api-b:
      path: /other/**
      serviceId: service-other