server:
  port: 8763

spring:
  application:
    name: service-hi
  zipkin:
    base-url: http://134.175.126.108:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/